### PR TITLE
Add new requirement fields for the template

### PR DESCRIPTION
**Pull request by egekorkan**
Please see https://github.com/w3c/wot-usecases/issues/192#issuecomment-1090442207 and also the first comment of the issue

### CODE REVIEW

**Comment by egekorkan** [comment]
@mlagally do you generate the html version from md ?

**Comment by mlagally** [comment]
@egekorkan 
There's a converter which is used by @chachamimm to do the conversion.

**Comment by chachamimm** [comment]
I think it is important to change the template for use cases.

However, templates need to be consistent and should not be changed. Because it is not good that there are differences between use cases written in the old version of the template and use cases written in the new version of the template. So I think this change should be made for the next charter.

And I think we should discuss a new version use cases template in the TF rather than changing ​​part of the current version template.

Use cases template is used by WoT WG/IG members and non WoT WG/IG members. So the template  should be easy for them to understand. If it is complicate, they are not able to write.

WoT-JP CG will propose some new use cases for next charter. If it is possible, WoT-JP CG would like to use the new version template.

**Comment by mlagally** [comment]
@chachamimm @egekorkan , let's discuss in tomorrow's use cases call.

**Comment by mlagally** [comment]
UC call on Dec 6th:

Consider moving these requirements as subsections to the requirements.md. This template should just list the potential topics for requirements, details should be described in a thorough analysis in the requirements template.

We will improve the templates in the next charter period, don't change them for the remaining time.
If a submitter of a UC already knows detailed requirements, he should already provide that information as a separate requirements file.

**Comment by egekorkan** [comment]
Some comments:
- The IG Charter goes for another year, I do not see a reason to wait for a year. Did you mean the WG charter?

> If a submitter of a UC already knows detailed requirements, he should already provide that information as a separate requirements file.

I really have to stress on this. If the UC submitter does not know the details, the UC Task Force should work to extract them and UCs should not be merged into the main document unless the details are known. Without the details, we cannot use the use case for the development of the standard. #200 is really nice but does not bring any new requirements or feature requests for any of our documents.

**Comment by mlagally** [comment]
UC call on Jan 31:
Agree to merge

**Pull request merged**
