### PR TITLE
Addition of linked building data use case combining TD with BIM Data

### PR DESCRIPTION
**Pull request by GeorgFerdinandSchneider**
Dear all,

we are happy to finally submit our draft use case description on Thing Descriptions of IoT components in Buildings.

We are happy to receive your comments and will participate in the next upcoming call of WoT Use Cases.

The use cases has been prepared by @chung-edison, @HervePruvost and me. We would like to acknowledge the valuable feedback by Sebastian Käbisch, Maria Husmann, @vcharpenay and @gtfierro.

Best

Georg

***
<a href="https://pr-preview.s3.amazonaws.com/w3c-lbd-cg/wot-usecases/pull/102.html" title="Last updated on Mar 4, 2021, 11:48 AM UTC (61e26b2)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/wot-usecases/102/7fb6cbc...w3c-lbd-cg:61e26b2.html" title="Last updated on Mar 4, 2021, 11:48 AM UTC (61e26b2)">Diff</a>

### CODE REVIEW

**Comment by sebastiankb** [comment]
Many thanks for this contribution. 

Some questions:

Example 1 includes a definition of 
```
"ssns:hasSystemCapability": {
        "@id": "osh:Kitchen-temp-Sensor-Capa",
        "@type": "ssns:SystemCapability",
        "ssns:hasSystemProperty": {
            "@type": ["ssns:MeasurementRange"],
            "schema:minValue": 0.0,
            "schema:maxValue": 40.0,
            "schema:unitCode": "om:degreeCelsius"
        }
```

What is the motivation to have this definition again and why not doing this within the property `Kitchen-temp`? Please note that TD comes with `maximum` and `minimum` terms that can be also used within properties. 

Is it possible to rename the property and/or action names to be more human readable. E.g., "Kitchen-tempS" to "temperatureSetpoint".  Or is there a special reason why there is also the location provided in the interaction names? 

Example 4 shows an example that is based on a REST API. Can you provide more background about the API, is this defined in the context of BOT? How is the URL query is mapped to the triples as shown in the SPARQL query (Example 3).

**Comment by HervePruvost** [comment]
Dear Sebastian,

First I would answer questions 2 and 3. Maybe for question 1 can @chung-edison give some input.  

Regarding "Kitchen-tempS", I think that is no problem to rename it as you proposed. The initial names of entities (same as for IRIs in ontology) are chosen for practical readability and should be flexible. So we can choose something even more human readable. The actual semantics and relationships with other entities (like Kitchen) is rather provided by the underlying ontology and the TD.  

Regarding the REST end point, this is one example about how one developer could implement it. In fact this end points and underlying REST server is a work in progress by me in some research project. But basically yes, this relies on BOT concepts and reuse them. The API itself is defined using the classical [OpenAPI specification](https://www.openapis.org/). 
Some REST server is then implemented (under work), here as a Node.JS server coded in JS (could be some other programming language). A data binding is then made between the server and the underlying backend storage, here a triple store, but this binding methods are similar by SQL. The REST server relies on the query language of the specific backend storage (SQL queries for SQL, SPARQL for RDF) and call these queries. Basically this data binding follows some usual process when making REST APIs. The result is then information resp. a subset of the backend model that is structured in classical JSON. The end point is then used by some application that consumes plain JSON rather than triples. This was some requirements made to us to have some example of more common API endpoints as SPARQL is less popular in the Web community.   

Another interesting approach to achieve the same is to use [GraphQL](https://www.w3.org/community/graphql-rdf/). I have not tested it deeply enough, but it can provide a flexbile variant to query RDF into JSON over the Web.
Another variant is to query the triple store and produce directly JSON-LD through the end point. But again, for applications that rather use common JSON or some custom JSON schemas, they would rather rely on the example 4.

I hope I could provide relevant answers. I can update the use case decription in that sense.
Best
Hervé

**Comment by GeorgFerdinandSchneider** [comment]
Dear @sebastiankb,

thanks for your response. I can contribute to the answers by @HervePruvost:

- Q2 Naming: Sure, we are free to pick something more meaningful for the human reader
- Q3 REST API: Answered by @HervePruvost [above](https://github.com/w3c/wot-usecases/pull/102#issuecomment-791352564)
- Q1 use of `ssns:MeasurementRange`: In our first versions we used the TD `maximum `and `minimum` properties to specify the measurement range  of the example temperature sensor. During the refinement of our description we understood that the properties have a slightly different meaning. To be strict in the descriptions we added the measurement range of the described sensor using `ssns:MeasurementRange` for the sake of preciseness. @chung-edison @vcharpenay feel free to further add or clarify on this topic.

Items to be discussed from my side are:
- The title of the use case. We are happy to receive suggestions
- potential merge of use case "[Smart Building](https://w3c.github.io/wot-usecases/#smart-building)"

Best

Georg

**Comment by sebastiankb** [comment]
many thanks for your feedback. Today we have a use case call (2pm CET). It would be great when you can join the call.

**Comment by GeorgFerdinandSchneider** [comment]
From the WoT use case discussion today I took some notes/ take aways:
- Need to reference to Building Information Modelling
-> Add reference to  [Sacks, R., Eastman, C., Lee, G., & Teicholz, P. (2018). BIM handbook: A guide to building information modeling for owners, designers, engineers, contractors, and facility managers. John Wiley & Sons](https://doi.org/10.1002/9781119287568).
- Dependency connections needed to link to [WoT Discovery and Geolocation](https://github.com/w3c/wot-discovery/blob/main/proposals/geolocation.md)
- Suggested new title: "Automated Smart Building Management"
- Kaz checks if affiliation of authors should be W3C LBD CG

**Comment by HervePruvost** [comment]
> From the WoT use case discussion today I took some notes/ take aways:
> 
> * Need to reference to Building Information Modelling
>   -> Add reference to  [Sacks, R., Eastman, C., Lee, G., & Teicholz, P. (2018). BIM handbook: A guide to building information modeling for owners, designers, engineers, contractors, and facility managers. John Wiley & Sons](https://doi.org/10.1002/9781119287568).
> * Dependency connections needed to link to [WoT Discovery and Geolocation](https://github.com/w3c/wot-discovery/blob/main/proposals/geolocation.md)
> * Suggested new title: "Automated Smart Building Management"
> * Kaz checks if affiliation of authors should be W3C LBD CG

I noted this point also:
* relationships to some existing communication protocols (OPC-UA, MQTT...)

**Comment by mlagally** [comment]
@GeorgFerdinandSchneider @HervePruvost 

As agreed in today's UC call, I have copied your contribution to https://github.com/w3c/wot-usecases/pull/112 
I will merge this now to have a solid base for review that contains all contributions.

Feel free to create additional MRs on top of the contents of main branch.

**Comment by mlagally** [comment]
The contribution has been added as per Georg's comment above.

**Pull request closed without merging**
