### PR TITLE
Update coverage.csv - Discovery

### PR DESCRIPTION
**Pull request by mmccool**

### CODE REVIEW

**Review by mlagally — COMMENTED** [review]
Thanks @mmccool for the update.

What does data-based indicate?
The term FoI is not widely known, is there a better alternative?
Does "ad-hoc" stand for "ad-hoc networking"?

**Comment by mmccool** [comment]
- FoI = feature of interest (from SSN).  I can expand it.

**Comment by mmccool** [comment]
"data-based" means a search over the actual data returned by devices, including historical data, as opposed to what we currently support, which is search over *metadata* (TDs).  This may or may not be considered a "discovery" topic (it might be a new deliverable), but it was mentioned in a large number of use cases.

**Comment by mmccool** [comment]
"ad-hoc" means "ad-hoc" discovery.  For example, I am walking in a mall and want to access a local service, say to call an elevator.  This is in contrast to use of discovery during installation or for development.  Probably I should look again at all the use cases and add either "ad-hoc" or "dev" or "install" to all of them...

**Comment by mmccool** [comment]
Merge conflicts fixed.  Expanded FoI to "feature of interest" and cited SSH, added defn for data-based and ad-hoc in comments column on first use.  As agreed, will merge.

**Pull request merged**
