### PR TITLE
added pending corrections

### PR DESCRIPTION
**Pull request by HervePruvost**
added the corrections discussed in last WoT UC meeting and listed in [#102](https://github.com/w3c/wot-usecases/pull/102).
Took [#112](https://github.com/w3c/wot-usecases/pull/112) as basis.
MR open for further comments or change needs.

***
<a href="https://pr-preview.s3.amazonaws.com/w3c-lbd-cg/wot-usecases/pull/124.html" title="Last updated on Apr 12, 2021, 2:18 PM UTC (096e6fa)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/wot-usecases/124/1020e9a...w3c-lbd-cg:096e6fa.html" title="Last updated on Apr 12, 2021, 2:18 PM UTC (096e6fa)">Diff</a>

### CODE REVIEW

**Comment by HervePruvost** [comment]
@GeorgFerdinandSchneider, @chung-edison please review.

**Comment by mlagally** [comment]
@HervePruvost 
Thanks, these proposed changes look very reasonable, Georg, Edison, can you please confirm?

**Comment by chung-edison** [comment]
@HervePruvost @mlagally 
Agreed, changes look fine.

**Comment by GeorgFerdinandSchneider** [comment]
Thanks @HervePruvost for adding the modifications. @mlagally changes are all good, thanks for merging.

**Pull request merged**
