### PR TITLE
Add new use cases for smart agriculture-Milking

### PR DESCRIPTION
**Pull request by mhchoi76**
Propose new use case for automatic milking system for dairy farm

***
<a href="https://pr-preview.s3.amazonaws.com/mhchoi76/wot-usecases/pull/200.html" title="Last updated on Dec 20, 2022, 9:09 PM UTC (26cc9e8)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/wot-usecases/200/e136245...mhchoi76:26cc9e8.html" title="Last updated on Dec 20, 2022, 9:09 PM UTC (26cc9e8)">Diff</a>

### CODE REVIEW

**Comment by mhchoi76** [comment]
This PR is related with issue #195 . @mmccool , @mlagally, Could you review this.

**Comment by mhchoi76** [comment]
@mmccool , @mlagally, @ashimura , Could you review this new use case, smart agriculture-milking?

**Comment by mlagally** [comment]
UC call on Dec 6th:
We reviewed the use case description and consider it very relevant for inclusion into the next version of the document.
A few suggestions:
- security requirement should be elaborated: for example key management on the LAN to support TLS
- RFID tags are only one example, other options are QR or bar codes
- gaps: latencies of control systems are also an aspect of motivation for an edge device

Can you please update the draft, we plan to revisit this in the next UC call on December 20th.

**Comment by mhchoi76** [comment]
Updated the texts of this use case according to the comments from yesterday meeting.
@mlagally, @mmccool, @ashimura,  Could you please check and review this updated use case?

Thank you so much.

**Pull request merged**
